### PR TITLE
Use the latest rubies on Travis

### PR DESCRIPTION
**Pull request by koic**

### CODE REVIEW

**Comment by hrysd** [comment]
Thank you for sending a patch.
Could you drop 1.9.3 and 2.0.0 from travis.yml? I think it is no longer needed ;)

**Comment by koic** [comment]
Thanks for your reply.

As a matter of fact, There are still people who are using Ruby 1.9 and 2.0.
I think that we will drop 1.9.3 and 2.0.0 from travis.yml when these become a hindrance to implementation of this library.

What do you think about it?

**Comment by hrysd** [comment]
[exception_notification](https://github.com/smartinez87/exception_notification#requirements) seems to not support 1.9.3. So there are no reason to support 1.9.3.

**Comment by koic** [comment]
I got it! Shall I drop 1.9.3 from .travis.yml?

**Comment by hrysd** [comment]
Yes please!

**Comment by koic** [comment]
I'm done :octocat:

**Comment by hrysd** [comment]
Looks good!

**Comment by koic** [comment]
Thanks!

**Pull request merged**
